# Generated by Django 5.0.3 on 2024-03-11 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0002_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
