# Generated by Django 5.0.3 on 2024-03-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockmanager", "0003_investment_date_alter_investment_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="bourse",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="name",
        ),
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name="Bourse",
        ),
    ]
